# Generated by Django 2.2.4 on 2020-11-09 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_code', models.CharField(max_length=16, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=20)),
                ('description', models.TextField()),
                ('score_mode', models.CharField(choices=[('SUM', 'SUM'), ('GROUP_MIN', 'GROUP_MIN')], max_length=20)),
                ('score_parameter', models.TextField()),
                ('time_limit', models.FloatField(default=1)),
                ('memory_limit', models.IntegerField(default=256)),
                ('diff_mode', models.CharField(choices=[('C1', 'C1')], max_length=20)),
                ('custom_grader', models.FileField(blank=True, upload_to='')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('tags', models.ManyToManyField(to='problems.Tag')),
            ],
        ),
    ]
