# Generated by Django 2.2.4 on 2020-11-05 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=8, unique=True)),
                ('compiler', models.CharField(max_length=256)),
                ('source_extension', models.CharField(default='', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField()),
                ('status', models.CharField(default='PENDING_STATUS', max_length=100)),
                ('test_counts', models.IntegerField(default=0)),
                ('result', models.CharField(default='', max_length=256)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.Language', to_field='language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem', to_field='problem_code')),
            ],
        ),
    ]
