# Generated by Django 2.2.4 on 2020-06-05 15:19

from django.db import migrations, models
import submissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING_STATUS'), ('JUDGING', 'JUDGING_STATUS'), ('FINISHED', 'FINISHED_STATUS')], default=submissions.models.SubmissionStatus('PENDING_STATUS'), max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='test_counts',
            field=models.IntegerField(default=0),
        ),
    ]
