# Generated by Django 2.2.4 on 2020-06-05 19:16

from django.db import migrations, models
import submissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='source_code',
            field=models.FileField(upload_to=submissions.models.get_encrypted_file_path),
        ),
    ]
